### ISSUE TITLE
Nertivia "softlock" when joining a server

### ISSUE THREAD

**Issue by Luyler** [supertiger1234/Nertivia-Client#200] opened 2020-09-25 00:54 UTC
Device + OS:
Windows 10 PC

Bug:
When joining a server using an invite link I experienced a TON of lag, the client even had to reconnect a few times.
video: https://youtu.be/V6DyQxAofIE
^it took over 3 minutes in total to authenticate, and then it froze again.
I'm now stuck; whenever I open Nertivia it will freeze and reload, and repeat

Edit: 10 minutes into trying to reload Nertivia it constantly shows this page.
![screenshot](https://user-images.githubusercontent.com/65765206/94214663-1ea03c80-fea8-11ea-8abc-746bd749a9d3.png)

Edit 2: I literally can't open Nertivia without it freezing and crashing.
video: https://youtu.be/Fq6Qtp70M4A

Edit 3: Apparently it happens when someone "quotes a quote of a quote"

**Comment by Brecert** [comment] 2020-09-28 21:59
I have reason to believe this was caused by quote nesting, I am closing this for now as quote nesting performance issues were fixed in #214.

**Comment by Brecert** [comment] 2020-09-28 22:00
If the issue was not fixed please re-open this issue.

**Closed** 2020-09-28 22:00 UTC
Labels: bug
