### ISSUE TITLE
Emojiiss

### ISSUE THREAD

**Issue by MitchellBlack506** [supertiger1234/Nertivia-Client#63] opened 2020-04-28 21:24 UTC
:P :) xD turns into predefined emojis

**Comment by Brecert** [comment] 2020-09-29 16:17
While #96 is a duplicate of this, it's had more discussion and was a little more clear and defined.

I'll be closing this, any future discussion about emojifying of text should happen in #96.

**Closed by Brecert** 2020-09-29 16:17 UTC
Labels: enhancement
